---
- name: disable postgresql module
  command: dnf module disable postgresql -y

- name: Ensure PostgreSQL packages are installed
  dnf:
    name: "{{ pg_packages }}"
    state: present
    enablerepo: "{{ pg_enablerepo | default(omit, true) }}"
    # Don't let postgresql-contrib cause the /usr/bin/python symlink
    # to be installed, which breaks later Ansible runs on Fedora 30,
    # and affects system behavior in multiple ways.
   # exclude: python-unversioned-command

- name: Set postgres user's OS password
  user:
    name: "{{ pg_user }}"
    password: "{{ pg_user_password | password_hash('sha512') }}"
    update_password: always
    state: present
